--- 
jobs: 
  steps: 
    name: "Python Style Checker"
    run: |
        pip install --upgrade-pip
        pip install pycodestyle
        pycodestyle templog.py
    uses: andymckay/pycodestyle-action@0.1.3
name: "Python Style Checker"
true: 
  - push
