name: Python Style Checker
on: [push]

jobs:
  runs-on: ubuntu-latest
  steps:
    name: Python Style Checker
    uses: andymckay/pycodestyle-action@0.1.3
    run: |
      pip install --upgrade-pip
      pip install pycodestyle
      pycodestyle templog.py
