name: Style Checker for Python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Echo test
      run: echo Hello, world!
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
