name: Python Style Checker
on: [push]
  
jobs:
  runs-on: [ubuntu-latest]
    steps:
    - uses: andymckay/pycodestyle-action@0.1.3
    - name: Python Style Checker
      run: |
        pip install --upgrade-pip
        pip install pycodestyle
        pycodestyle templog.py
